package com.smartshop.sovereign.util

import com.smartshop.sovereign.domain.model.ReceiptData
import com.smartshop.sovereign.domain.model.ReceiptItem
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Receipt Generator - Template Engine Approach
 * Builds formatted receipt string with placeholders
 */
@Singleton
class ReceiptGenerator @Inject constructor() {

    /**
     * Master template - can be internationalized
     */
    private val template = """
========================================
           %SHOPNAME%
========================================
TEL:  %SHOPTEL%
CASHIER: %SHOPKEEPER%
----------------------------------------
DATE: %DATE%
REF:  %TXN_REF%
----------------------------------------


ITEM          QTY    PRICE        TOTAL
----------------------------------------
%ITEM_LIST%
----------------------------------------


SUBTOTAL:                   UGX %SUBTOTAL%
TAX (Incl):                  UGX %TAX%
========================================
TOTAL:                      UGX %TOTAL%
========================================


    Thank you for your business!
      Powering %SHOP_NICHE%
       Generated by SmartShop
========================================
    """.trimIndent()

    /**
     * Generate receipt string from data
     */
    fun generate(data: ReceiptData): String {
        // Build item list with monospace alignment
        val itemList = StringBuilder()
        data.items.forEach { item ->
            val line = String.format(
                "%-13s %-4d %8d %12d\n",
                item.name.take(13),
                item.quantity,
                item.unitPrice,
                item.totalPrice
            )
            itemList.append(line)
        }

        // Replace all placeholders
        return template
            .replace("%SHOPNAME%", data.shopName)
            .replace("%SHOPTEL%", data.shopTel)
            .replace("%SHOPKEEPER%", data.cashierName)
            .replace("%DATE%", data.timestamp)
            .replace("%TXN_REF%", data.transactionId)
            .replace("%ITEM_LIST%", itemList.toString())
            .replace("%SUBTOTAL%", formatAmount(data.subtotal))
            .replace("%TAX%", formatAmount(data.tax))
            .replace("%TOTAL%", formatAmount(data.total))
            .replace("%SHOP_NICHE%", data.nicheType)
    }

    private fun formatAmount(cents: Long): String {
        return String.format("%,d", cents)
    }
}